version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test
      - run: make docker_build 
workflows:
  basic:
    jobs:
      - build-and-test